### ISSUE TITLE
I want to reference your repo. 

### ISSUE THREAD

**Issue by amirbehjat** [bobzwik/Quadcopter_SimCon#43]
Hi,

I want to reference your repo.  If you want please let me know your full name and I can add it to the references section. Otherwise, I can only cite the repo but without your name because I am not sure if this is your last name or not.
BTW, Thanks for the code.

**Comment by amirbehjat** [comment]
Also, please tell me which UAV hardware is used here. Is it based o na commercial UAV? Sorry that I ask too many questions.

**Comment by tjards** [comment]
Hi Amir,

Thanks for your interest in our work. This repo is an implementation of the
following paper:

P. T. Jardine, S. N. Givigi and S. Yousefi, "Leveraging Data Engineering to
Improve Unmanned Aerial Vehicle Control Design," in *IEEE Systems Journal*,
doi: 10.1109/JSYST.2020.3003203.

As for the Quadcopter UAV, we used the simulation setup and model developed
by John Bass here <https://github.com/bobzwik/Quadcopter_SimCon>.

Cheers,

Travis

**Comment by amirbehjat** [comment]
Thanks a lot. This helps a lot

**Comment by tjards** [comment]
The license says the author's name is John Bass.

**Comment by amirbehjat** [comment]
Thanks a lot.  I see.. Do you have his affiliation?

**Comment by amirbehjat** [comment]
thank you
