### ISSUE TITLE
Warning: Axes3D -- solved

### ISSUE THREAD

**Issue by ahah43** [bobzwik/Quadcopter_SimCon#46]
For python version > 3.6:

When running the current code, python raises the following warning:

**\Quadcopter_SimCon-master\Simulation\utils\animation.py:40: MatplotlibDeprecationWarning: Axes3D(fig) adding itself to the figure is deprecated since 3.4. Pass the keyword argument auto_add_to_figure=False and use fig.add_axes(ax) to suppress this warning. The default value of auto_add_to_figure will change to False in mpl3.5 and True values will no longer work in 3.6.  This is consistent with other Axes classes.
  ax = p3.Axes3D(fig)**

To solve this: open ./Simulation/utils/animation.py and replace line 40:
**ax = p3.Axes3D(fig)**

with the following two lines:

**ax = p3.Axes3D(fig,auto_add_to_figure=False)
fig.add_axes(ax)**

**Comment by pynbbz** [comment]
> For python version > 3.6:
> 
> When running the current code, python raises the following warning:
> 
> **\Quadcopter_SimCon-master\Simulation\utils\animation.py:40: MatplotlibDeprecationWarning: Axes3D(fig) adding itself to the figure is deprecated since 3.4. Pass the keyword argument auto_add_to_figure=False and use fig.add_axes(ax) to suppress this warning. The default value of auto_add_to_figure will change to False in mpl3.5 and True values will no longer work in 3.6. This is consistent with other Axes classes. ax = p3.Axes3D(fig)**
> 
> To solve this: open ./Simulation/utils/animation.py and replace line 40: **ax = p3.Axes3D(fig)**
> 
> with the following two lines:
> 
> **ax = p3.Axes3D(fig,auto_add_to_figure=False) fig.add_axes(ax)**

Thank you! that was driving me crazy. it's working now
